// Critical scroll-animation frame sequences. These are otherwise lazy-loaded
// only when scrolled near, which makes them pop in / fail to animate right after
// the intro loader dismisses. The loader preloads them (DESKTOP ONLY — see
// preloadCriticalAssets) so they are cached before it reveals the page.
//
// RESPONSIVE FRAMES: each scrubber decodes its frames to raw RGBA bitmaps held in
// memory for the page's whole life (width x height x 4 bytes per frame). At full
// resolution the three sequences pin ~470 MB — past iOS Safari's per-tab ceiling,
// the main cause of phone scroll lag / tab reloads. So phones (<=767px) get a
// lighter `-sm` variant (fewer frames + a modest downscale, generated by
// scripts/build-mobile-frames.cjs) holding ~180 MB instead; desktop/tablet keep
// the full-res sequences. `pickFrames` chooses per device; the scrubbers and the
// preloader both go through it so they can never draw a different set than was
// warmed.
//
// NOTE: keep these in sync with the scrubber components AND the build script:
//   - laptop-frames(-sm)  -> Features/ChibiLaptopScene.tsx
//   - action-frames(-sm)  -> Features/ActionLaptop.tsx
//   - peace(-sm)          -> PeaceScrubber.tsx

const pad2 = (i: number) => String(i).padStart(2, '0');
const pad3 = (i: number) => String(i).padStart(3, '0');

// Build a frame-URL list that loads every `step`-th source frame (always
// including the last, so the animation reaches its final state). Dropping the
// in-between frames is imperceptible at scroll speed but roughly divides the
// decoded-bitmap memory AND the download by `step`. If a scrub ever looks
// steppy on a slow, deliberate scroll, lower that sequence's step toward 1.
function sampled(
  total: number,
  step: number,
  name: (i: number) => string
): string[] {
  const indices: number[] = [];
  for (let i = 0; i < total; i += step) indices.push(i);
  if (indices[indices.length - 1] !== total - 1) indices.push(total - 1);
  return indices.map(name);
}

// The `-sm` folders are pre-sampled + pre-downscaled by the build script and
// named sequentially frame00.webp.. so the list is a plain count.
function seq(dir: string, count: number): string[] {
  return Array.from(
    { length: count },
    (_, i) => `/images/${dir}/frame${pad2(i)}.webp`
  );
}

// Repeat one entry of a frame list in place to create a deliberate scroll
// "hold" — the scrub dwells on that frame instead of passing straight through.
// Repeated URLs share a single decoded bitmap (getFrameImage dedupes by URL),
// so even a long hold costs no extra memory. `copies` is how many EXTRA times
// the frame shows (it appears copies + 1 times total). Done at the list level —
// not by copying source PNGs — because the sequences are sampled down, which
// would thin duplicated source files out unpredictably.
function repeatAt(frames: string[], at: number, copies: number): string[] {
  if (at < 0 || at >= frames.length || copies <= 0) return frames;
  const dup = Array.from({ length: copies }, () => frames[at]);
  return [...frames.slice(0, at + 1), ...dup, ...frames.slice(at + 1)];
}

// Hold the "GIA in action" laptop on the HOOK-FOR-SAVES screen (source frame 95)
// so it's readable before the lid closes. Phones get fewer copies — their `-sm`
// set has ~half the frames, so the same dwell would feel disproportionately long.
const ACTION_HOLD_FRAME = 95;
const ACTION_HOLD_COPIES = 5;
const ACTION_HOLD_COPIES_SM = 3;

// ── Full-res sequences (desktop + tablet) ──────────────────────────────────
// Source folders hold the full sequences (120 / 137 / 70); we sample them down.
export const LAPTOP_FRAMES_FULL = sampled(
  120,
  2,
  (i) => `/images/laptop-frames/final2_prob${3000 + i}.webp`
);
// 137-frame export (transparent, cut out by process-action-frames.cjs) sampled
// to ~47 — proportionate to the old 39-frame set, not 137; the full set would
// pin ~373 MB of decoded bitmaps for this one scrubber. Then the hold frame is
// spliced in (it isn't a sampled index) and repeated to dwell on it.
const actionUrl = (i: number) =>
  `/images/action-frames/laptop-screen${pad3(i)}.webp`;
export const ACTION_FRAMES_FULL = (() => {
  const base = sampled(137, 3, actionUrl);
  const holdUrl = actionUrl(ACTION_HOLD_FRAME);
  let at = base.indexOf(holdUrl);
  let frames = base;
  if (at === -1) {
    // 95 isn't a sampled index (step 3); splice it into sequence order. The
    // zero-padded names sort by frame number, so the first URL that sorts after
    // it is the insertion point.
    at = base.findIndex((u) => u > holdUrl);
    at = at === -1 ? base.length : at;
    frames = [...base.slice(0, at), holdUrl, ...base.slice(at)];
  }
  return repeatAt(frames, at, ACTION_HOLD_COPIES);
})();
export const PEACE_FRAMES_FULL = sampled(
  70,
  2,
  (i) => `/images/peace/gia-peace${pad2(i)}.webp`
);

// ── Phone sequences (<=767px) ──────────────────────────────────────────────
// Counts MUST match the build script's `outCount` for each job.
export const LAPTOP_FRAMES_SM = seq('laptop-frames-sm', 28);
// Same HOOK-FOR-SAVES hold as the full set. The `-sm` frames are resampled +
// renamed sequentially, so map frame 95's place in the 137-frame source to the
// nearest `-sm` frame and dwell there.
export const ACTION_FRAMES_SM = (() => {
  const base = seq('action-frames-sm', 24);
  const at = Math.round((ACTION_HOLD_FRAME / 136) * (base.length - 1));
  return repeatAt(base, at, ACTION_HOLD_COPIES_SM);
})();
export const PEACE_FRAMES_SM = seq('peace-sm', 18);

/**
 * True on phones (the band that renders the mobile Features layout). Drives the
 * lighter frame VARIANT. SSR-safe (returns false on the server, so the
 * server/desktop path is the full set).
 */
export function prefersSmallFrames(): boolean {
  if (typeof window === 'undefined' || !window.matchMedia) return false;
  return window.matchMedia('(max-width: 767px)').matches;
}

/**
 * True on touch devices (phones AND tablets). Drives the memory LIFECYCLE: these
 * devices lazy-load their scrub frames and release them when the section scrolls
 * far away (so the three sequences are never all decoded at once), instead of
 * eagerly preloading + holding everything. Desktop (fine pointer) keeps frames
 * warm — it has the RAM and we'd rather avoid any first-scroll pop-in.
 * Independent of `prefersSmallFrames`: a tablet evicts but still uses full-res.
 */
export function prefersFrameEviction(): boolean {
  if (typeof window === 'undefined' || !window.matchMedia) return false;
  return window.matchMedia('(pointer: coarse)').matches;
}

/**
 * Drop a sequence's frames from the shared cache so their decoded bitmaps can be
 * garbage-collected. The caller must also clear its own references (imagesRef);
 * re-acquiring later just calls getFrameImage again, which re-fetches + decodes.
 */
export function releaseFrames(urls: string[]): void {
  for (const url of urls) frameImages.delete(url);
}

/** Pick the device-appropriate frame list for a sequence. */
export function pickFrames(full: string[], sm: string[]): string[] {
  return prefersSmallFrames() ? sm : full;
}

// Single source of truth for every scroll-frame Image. Both the loader (warming
// the cache below) and the scrubber components request frames through
// `getFrameImage`, so each URL is downloaded, decoded, and held in memory
// exactly once. The map keeps the fetched resources alive (cached) for the
// page's lifetime; the scrubbers read the same instances straight from it.
const frameImages = new Map<string, HTMLImageElement>();

/** Get the shared Image for a frame URL, creating + kicking off its load once. */
export function getFrameImage(url: string): HTMLImageElement {
  let img = frameImages.get(url);
  if (!img) {
    img = new Image();
    img.src = url;
    frameImages.set(url, img);
  }
  return img;
}

let promise: Promise<void> | null = null;

/**
 * Preload (download) the critical frames so nothing pops in after reveal.
 *
 * Touch devices (phones + tablets) SKIP the scrub sequences: eagerly decoding
 * all three at load creates a memory + decode spike (on top of the loader
 * frames) right when the device is busiest — the worst moment for the iOS memory
 * ceiling. Their scrubbers lazy-load + release frames via the lifecycle observer
 * instead. Desktop has the headroom, so it still warms the full sequences to
 * avoid first-scroll pop-in.
 */
export function preloadCriticalAssets(): Promise<void> {
  if (typeof window === 'undefined') return Promise.resolve();
  if (promise) return promise;

  const urls = ['/images/gia-on-laptop.png'];
  if (!prefersFrameEviction()) {
    urls.push(
      ...LAPTOP_FRAMES_FULL,
      ...ACTION_FRAMES_FULL,
      ...PEACE_FRAMES_FULL
    );
  }

  promise = Promise.all(
    urls.map(
      (url) =>
        new Promise<void>((resolve) => {
          const img = getFrameImage(url);
          // Resolve on success or failure — never block readiness on one asset.
          if (img.complete) {
            resolve();
            return;
          }
          img.addEventListener('load', () => resolve(), { once: true });
          img.addEventListener('error', () => resolve(), { once: true });
        })
    )
  ).then(() => undefined);

  return promise;
}
